'use client';
import {DrawingCanvas} from './drawing';
import {readDrawing,hasDrawing,type Stroke} from '@/lib/drawing';
import LetterReader from './letter-reader';
import { IncomingEnvelope, SendingEnvelope } from './envelope';
import { PlacedSticker } from './sticker';
import { defaultStickerLayout, readStickers, type StickerPlacement } from '@/lib/sticker-layout';
import { translate } from '@/lib/messages';
import { Localized, useLanguage, LanguagePicker, countryName } from './language';

import { useEffect, useState } from 'react';
import PostalCat from './postal-cat';
import Achievements from './achievements';
import LoadingCat from './loading-cat';
import { fonts, stickerNames, specialItems, type Progress } from '@/lib/rewards';
import { Feather, BookOpen, Mail, Sparkles, Globe2, ShieldCheck, ArrowUpRight, Send, Gift, Play, Check, Clock3, Flag, Ban, Heart, ChevronRight } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Textarea } from '@/components/ui/textarea';
import { moods, items, checkDiary } from '@/lib/diary-rules';
type Entry={drawing?:string|null;stickers?:string|null;sticker_layout?:string|null;font?:string;id:string;body:string;mood:string;region:string;paper:string;sticker:string;created:number;reaction?:string;delivered?:number};
type State={discovered?:string[];progress?:Progress;signedIn:boolean;sent:Entry[];received:Entry[];collection:string[];today:number;bonus:boolean;drawn:boolean};
const empty:State={signedIn:false,sent:[],received:[],collection:[],today:0,bonus:false,drawn:false};
const moodNames=['晴れやか','おだやか','もやもや','しょんぼり','ひとやすみ'];
const sample:Entry={id:'sample',body:'帰り道、いつも通り過ぎる花屋さんで、小さな花束を買いました。\n\n誰かのためじゃなく、自分のために。\nそれだけで、いつもの部屋が少し違って見えました。\n\nあなたにも、今日ひとつ、小さなうれしいことがありますように。',mood:'🌤️',region:'フランス',paper:'plain',sticker:'🌷',created:0};
const sampleOriginal="Sur le chemin du retour, j’ai acheté un petit bouquet chez le fleuriste devant lequel je passe toujours.\n\nPas pour quelqu’un d’autre. Pour moi. Et ma chambre m’a semblé un peu différente.\n\nJ’espère que vous trouverez, vous aussi, un petit bonheur aujourd’hui.";
export default function Diary(){
 const {locale}=useLanguage();
 const [opened,setOpened]=useState<string[]>([]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('kotonoha-opened')||'[]');if(Array.isArray(saved))setOpened(saved.filter((id:unknown)=>typeof id==='string').slice(-500));}catch{}},[]);
 function reveal(){if(!selected)return;if(selected.id!=='sample'){setOpened(previous=>{const next=[...new Set([...previous,selected.id])].slice(-500);try{localStorage.setItem('kotonoha-opened',JSON.stringify(next));}catch{}return next;});}setModal('read');}
 const [stickers,setStickers]=useState<(StickerPlacement&{key:string})[]>([]);
 const [drawing,setDrawing]=useState<Stroke[]>([]),[writeMode,setWriteMode]=useState('text');
 useEffect(()=>{try{setDrawing(readDrawing(localStorage.getItem('kotonoha-drawing-draft')));}catch{}},[]);
 const [font,setFont]=useState('sans');
 const [authReady,setAuthReady]=useState<boolean|null>(null);
 const [tab,setTab]=useState('today'),[state,setState]=useState<State>(empty),[body,setBody]=useState(''),[mood,setMood]=useState('🌤️'),[region,setRegion]=useState('確認中'),[paper,setPaper]=useState('plain'),[notice,setNotice]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[modal,setModal]=useState(''),[selected,setSelected]=useState<Entry|null>(null),[reason,setReason]=useState('不適切な内容'),[prize,setPrize]=useState(''),[book,setBook]=useState('received'),[date,setDate]=useState('今日');

 useEffect(()=>{if(!loading)try{localStorage.setItem('kotonoha-drawing-draft',JSON.stringify(drawing));}catch{}},[drawing,loading]);
 async function refresh(silent=false){try{const r=await fetch('/api/diary',{credentials:'same-origin',cache:'no-store',signal:AbortSignal.timeout(15000)});const d:any=await r.json();if(typeof d.region==='string')setRegion(d.region);if(r.ok){setState(d);setError('');}else if(r.status===401){setState(empty);}else if(!silent)setError(d.error);}catch{if(!silent)setError('接続できませんでした。下書きはこの画面に残っています。');}finally{setLoading(false);}}
 useEffect(()=>{fetch('/api/auth/status').then(async r=>{if(!r.ok)throw new Error('auth');const d:any=await r.json();setAuthReady(d.ready===true);}).catch(()=>setAuthReady(false));const loginError=new URLSearchParams(window.location.search).get('login');if(loginError){setError(loginError==='cancelled'?'ログインをキャンセルしました。':loginError==='expired'?'ログインの有効時間が切れました。もう一度お試しください。':'Googleログインに失敗しました。もう一度お試しください。');history.replaceState(null,'',window.location.pathname);}refresh();try{setBody(localStorage.getItem('kotonoha-draft')||'');}catch{} const timer=setInterval(()=>refresh(true),30000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{setDate(new Intl.DateTimeFormat(locale,{timeZone:'Asia/Tokyo',month:'long',day:'numeric',weekday:'long'}).format(new Date()));},[locale]);
 useEffect(()=>{if(!loading)try{localStorage.setItem('kotonoha-draft',body);}catch{}},[body,loading]);
 useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'stage_diary',description:'日記の下書きを編集画面に設定します。送信はしません。',inputSchema:{type:'object',properties:{body:{type:'string',maxLength:1000}},required:['body'],additionalProperties:false},annotations:{readOnlyHint:false},execute(input:any){if(typeof input?.body!=='string'||input.body.length>1000)throw new Error('1,000文字以内の文字列が必要です');setBody(input.body);setTab('today');return {staged:true,sent:false};}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 async function act(data:Record<string,unknown>){if(busy)return null;setBusy(true);setError('');setNotice('');try{const r=await fetch('/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d:any=await r.json();if(!r.ok)throw new Error(d.error);setNotice(d.message);await refresh();return d;}catch(e){setError((e as Error).message);return null;}finally{setBusy(false);}}
 async function send(){const issue=checkDiary(body,hasDrawing(drawing));if(issue){setError(issue);return;}const d=await act({action:'send',body,drawing,mood,paper,stickers:stickers.map(({sticker,layout})=>({sticker,layout})),font});if(d){setBody('');setDrawing([]);setStickers([]);setModal('sent');}}
 function addSticker(sticker:string){setStickers(prev=>prev.length>=5||prev.filter(p=>p.sticker===sticker).length>=state.collection.filter(item=>item===sticker).length?prev:[...prev,{key:crypto.randomUUID(),sticker,layout:{...defaultStickerLayout,x:30+prev.length*12,y:35+prev.length*10}}]);}
 function open(e:Entry){setSelected(e);setModal(e.id==='sample'||(state.received.some(r=>r.id===e.id)&&!opened.includes(e.id))?'envelope':'read');}
 const limit=state.bonus?2:1,available=state.today<limit;
 const collected=[...new Set(state.collection)];
 const discovered=state.discovered??collected;
 const catalog=[...items,...specialItems];
 async function pet(eventId:string){try{const r=await fetch('/api/diary',{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'pet',eventId}),signal:AbortSignal.timeout(15000)});if(!r.ok)return;const d=await r.json() as {progress:Progress};setState(prev=>({...prev,progress:d.progress}));await refresh(true);return d.progress;}catch{return;}} 
 return <Localized><div className="app-shell">
 <header className="masthead"><a className="brand" href="/" aria-label="ことのは ホーム"><span className="brand-icon" aria-hidden="true"><Mail size={27}/></span><span>ことのは<small>KOTONOHA</small></span></a><span className="brand-note">ことばを運ぶ。ついでに、ぬくもりも。</span><div className="account-controls"><LanguagePicker/>{state.signedIn&&<span className="session-saved">ログイン状態を保存中</span>}{state.signedIn&&<form action="/api/auth/logout" method="post"><Button type="submit" variant="ghost">ログアウト</Button></form>}<button className="privacy-pill" onClick={()=>setModal('safety')}><ShieldCheck size={16}/>匿名でつながる</button></div></header>
 <Tabs value={tab} onValueChange={setTab} className="workspace">
 <aside className="sidebar"><p className="side-label">KOTONOHA POST OFFICE</p><TabsList className="main-nav"><TabsTrigger value="today"><Feather/>今日の日記</TabsTrigger><TabsTrigger value="book"><BookOpen/>交換日記帳<span className="nav-count">{state.received.length}</span></TabsTrigger><TabsTrigger value="collection"><Sparkles/>小さなコレクション</TabsTrigger></TabsList>
 <div className="side-bottom"><div className="daily-note"><span>上手に書くの、<br/>お休みしませんか。</span><p>「お昼がおいしかった」も、<br/>ちゃんと立派な一日です。</p><span className="note-stamp">名文不要。誤字に寛大。</span></div><button className="safety-link" onClick={()=>setModal('safety')}><ShieldCheck size={16}/>安心して使うために</button><p className="side-foot">ONE DAY, ONE CONNECTION.</p></div></aside>
 <main className="main-content">
 <div className="page-top"><span className="eyebrow">OPEN FOR FEELINGS</span><span className="date"><span className="date-dot"/>{date}</span></div>
 {loading&&<LoadingCat/>}
 {error&&<div role="alert" className="message error">{error}<Button variant="ghost" onClick={()=>refresh()}>再読み込み</Button></div>}{notice&&<div role="status" className="message">{notice}</div>}
 <TabsContent value="today"><div className="page-heading"><div><span className="chapter-label">01 / 今日のひとこと便</span><h1>今日のきもち、<br/><em>おあずかりします。</em></h1><p>大事件も、おやつの話も。名も知らない誰かへ、1日1通。</p></div><span className="quota"><Mail size={15}/>{loading?'読み込み中':available?'本日、1通受付中':'本日の受付、おしまい'}</span></div>
 <div className="today-grid"><section className="writing-area"><div className="mood-row"><span>今日の気分</span><div className="moods">{moods.map((m,i)=><button key={m} title={moodNames[i]} aria-label={moodNames[i]} aria-pressed={mood===m} onClick={()=>setMood(m)} className={mood===m?'active':''}>{m}</button>)}</div><span className="mood-label">{moodNames[moods.indexOf(mood)]}</span></div>
 <div className="writing-mode" role="group" aria-label="日記の書き方"><button type="button" aria-pressed={writeMode==='text'} onClick={()=>setWriteMode('text')}>文字</button><button type="button" aria-pressed={writeMode==='brush'} onClick={()=>setWriteMode('brush')}>筆・絵日記</button></div>
 <div className={'letter '+paper+' diary-font-'+font}><div className="letter-top"><span>Dear まだ知らない、あなた</span><span className="letter-number">{String(state.sent.length+1).padStart(3,'0')} / TODAY</span></div>{(writeMode==='brush'||drawing.length>0)&&<DrawingCanvas strokes={drawing} onChange={writeMode==='brush'?setDrawing:undefined} disabled={!available||busy}/>}<label className="sr-only" htmlFor="diary">今日の日記</label><div className={"sticker-canvas editable-canvas "+(writeMode==='brush'?'brush-mode':'')}><Textarea id="diary" className="diary-input" value={body} maxLength={1000} onChange={e=>setBody(e.target.value)} placeholder={'拝啓、どこかの誰かさん。\n\n今日のわたしは、こんな感じでした。\n（オチはなくても大丈夫。）'} disabled={!available||busy||writeMode==='brush'}/>{stickers.map((p,i)=><PlacedSticker key={p.key} sticker={p.sticker} layout={p.layout} onChange={layout=>setStickers(prev=>prev.map((s,j)=>j===i?{...s,layout}:s))} disabled={busy}/>)}</div><div className="letter-bottom"><span className="signature">{translate('From {country}の、誰かさん',locale,{country:countryName(region,locale)})}</span><span>{body.length} / 1,000</span></div></div>
 {stickers.length>0&&<div className="sticker-tools"><p>ドラッグで移動。タップして、四隅を動かすと回転・拡大縮小できます。</p><div className="sticker-control-actions">{stickers.map((p,i)=><button key={p.key} disabled={busy} onClick={()=>setStickers(prev=>prev.filter((_,j)=>j!==i))} aria-label={translate('ステッカー{number}を外す',locale,{number:i+1})}>{p.sticker} ×</button>)}</div></div>}
 <div className="customize"><button onClick={()=>setModal('decorate')}><Sparkles size={16}/>便箋・ステッカー<ChevronRight size={14}/></button><span className="detected-country"><Globe2 size={16}/>{countryName(region,locale)}<small>IPから自動判定</small></span></div>
 <label className="font-picker">日記の書体<select aria-label="日記のフォント" value={font} onChange={e=>setFont(e.target.value)}>{fonts.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select><small>相手にも、この書体で届きます。</small></label>
 <p className="safe-hint"><ShieldCheck size={15}/>本名・住所・連絡先は書かないでください。</p>
 <div className="send-row"><span><Clock3 size={14}/>少し時間をかけて、誰かのもとへ。</span>{state.signedIn?<Button className="send-button" disabled={busy||!available||loading||(!body.trim()&&!hasDrawing(drawing))} onClick={send}>{busy?'日記を預けています…':available?'このきもちを、投函する':'本日は閉店。また明日。'}<Send size={17}/></Button>:<Button className="send-button" disabled={!authReady} asChild={authReady===true}>{authReady?<a href="/api/auth/google" target="_top">Googleでログイン<Send size={17}/></a>:<span>{authReady===null?"ログイン設定を確認中…":"Googleログインは設定準備中"}</span>}</Button>}</div>
 <p className="reset-note">文字は1,000文字まで・絵だけでもOK・1日1通・日本時間の午前0時にリセット{!state.signedIn?' ／ 下書きはこの端末に保存されます。ログイン後は、このブラウザーで状態を保持します。':''}</p>
 </section>
 <aside className="right-column"><PostalCat signedIn={state.signedIn} progress={state.progress} onPet={pet} busy={busy} mood={mood} bodyLength={body.length} catMentioned={/ねこ|猫|cat|chat|고양이/i.test(body)}/><section className="mail-card"><div className="card-heading"><span className="eyebrow">SOMEWHERE IN THE WORLD</span><Globe2 size={18}/></div><h2>まだ見ぬ誰かの、<br/>なんでもない一日。</h2><p>日記をひとつ送ると、<br/>世界のどこかの一日が届きます。</p><div className="mail-status"><Clock3 size={15}/>{state.sent.length?'次のお便りをお届け待ち':'あなたの1通から、はじまります'}</div>{state.received.length>0&&<Button variant="outline" onClick={()=>open(state.received[0])}>届いた日記を読む</Button>}</section>
 <section className="gift-card"><div className="gift-heading"><span className="gift-emoji">🎁</span><span className="mini-tag">1日1回の贈りもの</span></div><h3>中身は、猫にもひみつ。</h3><p>1日1回、机の引き出しに小さな贈りもの。</p><button onClick={()=>{setTab('collection');}} className="text-cta">贈りものを開ける<ArrowUpRight size={18}/></button></section>
 <button className="ad-link" onClick={()=>setModal('ad')}><Play size={15}/><span>もう少し、書きたい日は<small>広告を見て、もう1通 · 準備中</small></span><ChevronRight size={16}/></button></aside></div>
 <section className="sample-row"><span className="sample-label">こんなお便りが届きます<span>架空の日記の見本</span></span><button onClick={()=>open(sample)}><span className="sample-flower">🌷</span><span>「誰かのためじゃなく、自分のために。」<small>フランスの、誰かさんから</small></span><ArrowUpRight size={20}/></button></section>
 </TabsContent>
 <TabsContent value="book"><div className="page-heading"><div><h1>交換日記帳</h1><p>誰かの「なんでもない」が、あなたの宝物になる。</p></div><BookOpen size={30}/></div><Tabs value={book} onValueChange={setBook}><TabsList><TabsTrigger value="received">届いた日記 {state.received.length}</TabsTrigger><TabsTrigger value="sent">送った日記 {state.sent.length}</TabsTrigger></TabsList>{['received','sent'].map(kind=><TabsContent key={kind} value={kind}><div className="book-grid">{(kind==='received'?state.received:state.sent).map(e=><button key={e.id} className={'book-card '+e.paper+' diary-font-'+(e.font||'sans')} onClick={()=>open(e)}><span className="book-meta">{e.mood} {countryName(e.region,locale)}<small>{new Date(e.created).toLocaleDateString(locale,{timeZone:'Asia/Tokyo'})}</small></span>{kind==='received'&&!opened.includes(e.id)?<div className="sealed-preview"><span aria-hidden="true">✉</span><strong>まだ開けていないお便り</strong><small>タップして封筒を開く</small></div>:<div>{e.drawing&&<DrawingCanvas strokes={readDrawing(e.drawing)}/>}<p data-i18n-skip>{e.body}</p></div>}<span className="book-meta">{readStickers(e).map(p=>p.sticker).join(' ')||'✉️'}<small>{kind==='sent'?(e.delivered?'お届け済み':'お届け待ち'):'日記をひらく'} {e.reaction}</small></span></button>)}</div>{!(kind==='received'?state.received:state.sent).length&&<div className="empty-state"><Mail size={48} strokeWidth={1}/><h2>{kind==='received'?'まだ白紙。のびしろしかない。':'あなたの言葉を、最初の1ページに。'}</h2><p>{kind==='received'?'日記を書くと、誰かのお便りを待つことができます。':'短い日記でも大丈夫。今日の気持ちを残してみませんか。'}</p><Button onClick={()=>setTab('today')}>今日の日記を書く<Feather size={16}/></Button><button className="sample-open" onClick={()=>open(sample)}>見本の日記を読んでみる</button></div>}</TabsContent>)}</Tabs></TabsContent>
 <TabsContent value="collection"><div className="page-heading"><div><h1>小さなコレクション</h1><p>役には立たないかも。でも、ちょっとうれしい。</p></div><span className="quota">{discovered.length} / {catalog.length} 種類</span></div><section className="gacha-panel"><Gift size={54} strokeWidth={1}/><div><span className="eyebrow">A LITTLE GIFT, EVERY DAY</span><h2>今日の、ちいさな運だめし。</h2><p>無料で1日1回。ステッカーや便箋が、ランダムでひとつ。</p><small>{translate('全{count}種類・各約{chance}% ／ 重複あり。特典ステッカーは行動で獲得。',locale,{count:items.length,chance:(100/items.length).toFixed(2)})}</small></div><Button disabled={busy||state.drawn||!state.signedIn} onClick={async()=>{const d=await act({action:'gacha'});if(d){setPrize(d.item);setModal('prize');}}}>{state.drawn?'今日は受け取り済み':'贈りものを開ける'}<Sparkles size={16}/></Button></section>{!state.signedIn&&<p className="safe-hint">Googleでログインすると贈りものを受け取り、コレクションに保存できます。</p>}<h3 className="collection-title">ステッカーと便箋 <span>手に入れたものは日記に添えられます</span></h3><div className="collection-grid">{catalog.map((item)=><div className={'collectible '+(discovered.includes(item)?'owned':'locked')} key={item}><span className={item.startsWith('paper-')?'paper-swatch '+item:'collectible-icon'}>{item.startsWith('paper-')?'Aa':item}</span><strong>{stickerNames[item]||item}</strong><small>{discovered.includes(item)?`所持数 ${state.collection.filter(x=>x===item).length} 枚`:specialItems.includes(item)?'行動のごほうび':'まだ出会っていません'}</small></div>)}</div><Achievements progress={state.progress} signedIn={state.signedIn}/></TabsContent>
 <footer className="page-footer"><span>ことのは</span><span>一日ひとつ、やさしいつながり。</span><Heart size={13}/></footer>
 </main></Tabs>
 <Dialog open={!!modal} onOpenChange={o=>{if(!o)setModal('');}}><DialogContent className="diary-dialog"><DialogTitle>{({envelope:'あなた宛てのお便りです。',read:selected?.id==='sample'?'フランスからのお便り · 見本':translate('{country}の、誰かさん',locale,{country:countryName(selected?.region??'どこか',locale)}),sent:'あなたの今日を、預かりました。',safety:'安心して、心を交換するために',ad:'もう1通の交換について',decorate:'日記に、小さな彩りを。',prize:'今日、出会った贈りもの。',report:'この日記を通報する',block:'この相手をブロックする'} as Record<string,string>)[modal]||'ことのは'}</DialogTitle><DialogDescription>{modal==='envelope'?'封筒をタップすると、日記がひらきます。':modal==='read'?'返信のかわりに、ひとつの気持ちを。':modal==='sent'?'日記は保存されています。同じ日に投函した相手が見つかり次第、お便りが届きます。':'あなたのペースで、楽しんでください。'}</DialogDescription>
 {modal==='envelope'&&selected&&<IncomingEnvelope key={selected.id} onOpen={reveal}/>}
 {modal==='read'&&selected&&<><LetterReader key={selected.id+locale} entry={selected} signedIn={state.signedIn} sampleOriginal={sampleOriginal}/><button className="translate" onClick={()=>setModal('envelope')}>もう一度、封筒から開く</button>{(selected.id==='sample'||state.received.some(e=>e.id===selected.id))&&<><div className="reactions">{['🤍','🌷','🫂','✨'].map((r,i)=><button title={['共感しました','ありがとう','そっとハグ','すてき'][i]} aria-label={['共感しました','ありがとう','そっとハグ','すてき'][i]} aria-pressed={selected.reaction===r} key={r} disabled={busy} onClick={async()=>{if(selected.id==='sample'){setSelected({...selected,reaction:r});return;}const d=await act({action:'react',id:selected.id,reaction:r});if(d)setSelected({...selected,reaction:r});}}>{r}</button>)}</div><small className="center-note">{selected.id==='sample'?'見本へのリアクションは保存・送信されません。':selected.reaction?'気持ちを届けました。':'ひとつだけ、気持ちを届ける'}</small></>}{selected.id!=='sample'&&state.received.some(e=>e.id===selected.id)&&<div className="report-actions"><button onClick={()=>setModal('report')}><Flag size={14}/>通報する</button><button onClick={()=>setModal('block')}><Ban size={14}/>ブロック</button></div>}</>}
 {modal==='sent'&&<div className="modal-center"><SendingEnvelope/><img className="sent-cat" src="/mascot-delivery.png" width="180" height="180" alt="日記を抱えるぽすと"/><p>ぽすとが、大事そうに抱えています。<br/>また日記帳をのぞいてみてください。</p><Button onClick={()=>{setModal('');setTab('book');}}>交換日記帳へ</Button></div>}
 {modal==='safety'&&<div className="safety-copy"><p><strong>名前のかわりに、国・地域だけ。</strong><br/>相手にアカウント情報は表示されません。投稿時のIPアドレスから国・地域を自動判定します。VPNなどの利用時は接続先の国になる場合があり、判定できないときは「どこか」と表示します。</p><p><strong>自分と相手のプライバシーを大切に。</strong><br/>本名、住所、連絡先、SNSのIDは書かないでください。送信時にルールによる自動チェックを行いますが、すべてを検出できるわけではありません。</p><p>手書き・絵日記の線や色も日記と一緒に保存し、交換相手に表示します。手書き部分は自動テキストチェック・翻訳の対象外です。</p><p><strong>つらい内容は、受け取らなくて大丈夫。</strong><br/>届いた日記から通報・ブロックできます。通報された日記は非表示になり、記録が保存されます。</p><p><strong>1日1通の、ゆっくりしたやりとり。</strong><br/>日本時間の午前0時にリセット。返信機能はありません。同じ日（日本時間）に投函された日記同士で交換します。相手がいないときは日記を預かり、お届けを待ちます。</p></div>}
 {modal==='ad'&&<div className="safety-copy"><Play size={36}/><p>広告を最後まで見ると、その日だけ追加で1通書ける機能を準備しています。</p><p>現在は広告サービス未接続のため利用できません。通常の日記交換と無料の贈りものは、そのまま楽しめます。</p></div>}
 {modal==='decorate'&&<div className="decoration-picker"><h3>便箋</h3><div className="choice-row">{['plain',...collected.filter(i=>i.startsWith('paper-'))].map(p=><button key={p} aria-pressed={paper===p} className={p} onClick={()=>setPaper(p)}>{p==='plain'?'いつもの便箋':p==='paper-blue'?'空色':'桃色'}{paper===p&&<Check size={16}/>}</button>)}</div><h3>ステッカー <small>{stickers.length} / 5</small></h3><div className="choice-row">{collected.filter(i=>!i.startsWith('paper-')).map(s=><button key={s} disabled={stickers.length>=5||stickers.filter(p=>p.sticker===s).length>=state.collection.filter(item=>item===s).length} onClick={()=>addSticker(s)}>{s} + <small>{state.collection.filter(item=>item===s).length-stickers.filter(p=>p.sticker===s).length}</small></button>)}</div><p>ステッカーは1通に5枚まで。投函が成功すると貼った枚数だけ消費します。便箋は繰り返し使えます。</p><div className="sticker-control-actions">{stickers.map((p,i)=><button key={p.key} onClick={()=>setStickers(prev=>prev.filter((_,j)=>j!==i))} aria-label={translate('ステッカー{number}を外す',locale,{number:i+1})}>{p.sticker} ×</button>)}</div><Button onClick={()=>setModal('')}>これにする</Button></div>}
 {modal==='prize'&&<div className="modal-center"><span className="prize">{prize.startsWith('paper-')?'💌':prize}</span><h2>{prize==='paper-blue'?'空色の便箋':prize==='paper-pink'?'桃色の便箋':'新しいステッカー'}</h2><p>コレクションに保存しました。日記に添えてみましょう。</p><Button onClick={()=>{if(prize.startsWith('paper-'))setPaper(prize);else addSticker(prize);setModal('');setTab('today');}}>今日の日記に使う</Button></div>}
 {modal==='report'&&<><label>通報理由<select className="reason-select" value={reason} onChange={e=>setReason(e.target.value)}>{['個人情報','攻撃的な内容','不適切な内容','その他'].map(r=><option key={r} value={r}>{r}</option>)}</select></label><p>この日記は非表示になり、通報内容が保存されます。</p><Button disabled={busy} onClick={async()=>{if(await act({action:'report',id:selected?.id,reason}))setModal('');}}>通報して非表示にする</Button></>}
 {modal==='block'&&<><p>この相手の日記を非表示にし、今後の交換対象から外します。</p><Button disabled={busy} onClick={async()=>{if(await act({action:'block',id:selected?.id}))setModal('');}}>ブロックする</Button></>}
 {error&&<p role="alert" className="dialog-error">{error}</p>}
 </DialogContent></Dialog>
 </div></Localized>;
}



