'use client';
import {useEffect,useState} from 'react';
import {profileIcons} from '@/lib/friends';
import {Localized,useLanguage} from './language';
export type Profile={code:string;nickname:string;icon:string;birthday:string;isBirthday:boolean;birthdayGift:boolean};
export type Friend={id:string;status:string;outgoing:boolean;code:string;nickname?:string;icon?:string;birthday?:string};
export default function Friends({profile,friends,letters,incoming,busy,signedIn,act,compose,open}:{profile?:Profile;friends:Friend[];letters:any[];incoming:string[];busy:boolean;signedIn:boolean;act:(d:Record<string,unknown>)=>Promise<any>;compose:(id:string)=>void;open:(e:any)=>void}){
 const {locale}=useLanguage();const [nickname,setNickname]=useState(''),[icon,setIcon]=useState('🐈'),[birthday,setBirthday]=useState(''),[code,setCode]=useState(''),[selected,setSelected]=useState('');
 useEffect(()=>{setNickname(profile?.nickname??'');setIcon(profile?.icon??'🐈');setBirthday(profile?.birthday??'');},[profile?.nickname,profile?.icon,profile?.birthday]);
 if(!signedIn)return <Localized><div className="empty-state"><h2>フレンド</h2><p>Googleでログインすると、プロフィールとフレンド機能を利用できます。</p><a href="/api/auth/google">Googleでログイン</a></div></Localized>;
 const active=friends.filter(f=>f.status==='accepted');
 return <Localized><div className="friends-page"><div className="page-heading"><div><h1>フレンド</h1><p>知っている誰かと、ひとことずつ。</p></div></div>
 <section className="profile-card"><h2>あなたのプロフィール</h2><p>アイコン・ニックネーム・誕生日は、承認したフレンドだけに表示されます。匿名交換には表示されません。</p><form onSubmit={async e=>{e.preventDefault();await act({action:'profile-save',nickname,icon,birthday});}}><div className="profile-icons" role="group" aria-label="アイコン">{profileIcons.map(i=><button type="button" key={i} aria-label={i} aria-pressed={icon===i} onClick={()=>setIcon(i)}>{i}</button>)}</div><label>ニックネーム<input required maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="off"/></label><label>誕生日（月-日）<input value={birthday} placeholder="MM-DD" pattern="[0-9]{2}-[0-9]{2}" maxLength={5} onChange={e=>setBirthday(e.target.value)} inputMode="text"/><small>年は保存しません。例：04-15。未設定でも利用できます。</small></label><button className="friend-primary" disabled={busy}>プロフィールを保存</button></form><label>あなたのフレンドコード<input readOnly value={profile?.code??''} onFocus={e=>e.target.select()} aria-label="あなたのフレンドコード"/></label><p>コードを相手に教えて、申請を承認するとフレンドになります。</p></section>
 <section className="profile-card"><h2>フレンドを追加</h2><form onSubmit={async e=>{e.preventDefault();if(await act({action:'friend-request',code:code.replace(/\s/g,'').toUpperCase()}))setCode('');}}><label>相手のフレンドコード<input required value={code} maxLength={32} onChange={e=>setCode(e.target.value)} autoComplete="off"/></label><button className="friend-primary" disabled={busy}>申請を送る</button></form>{friends.filter(f=>f.status==='pending').map(f=><div className="friend-request" key={f.id}><strong data-i18n-skip>{f.code}</strong><span>{f.outgoing?'承認待ち':'フレンド申請が届いています'}</span>{!f.outgoing&&<button disabled={busy} onClick={()=>act({action:'friend-accept',friendship:f.id})}>承認する</button>}<button disabled={busy} onClick={()=>act({action:'friend-remove',friendship:f.id})}>{f.outgoing?'申請を取り消す':'見送る'}</button></div>)}</section>
 <section className="profile-card"><h2>フレンドとの交換日記</h2><p>フレンド宛ては全体で1日1通。双方が投函すると開封できます。日付が違っても交換でき、相手が開封するまでは次の投函を待ちます。</p>{!active.length&&<p>まだフレンドはいません。</p>}<div className="friend-list">{active.map(f=><button key={f.id} className="friend-person" aria-pressed={selected===f.id} onClick={()=>setSelected(f.id)}><span data-i18n-skip>{f.icon} {f.nickname||f.code}</span>{f.birthday&&<small data-i18n-skip>🎂 {f.birthday}</small>}{incoming.includes(f.id)&&<small>お便りが待っています</small>}</button>)}</div>{active.filter(f=>f.id===selected).map(f=><div key={f.id}><div className="friend-actions"><button className="friend-primary" disabled={busy} onClick={()=>compose(f.id)}>このフレンドに書く</button><button disabled={busy} onClick={()=>{if(window.confirm('フレンドを解除しますか？交換途中の日記は取り消されます。'))act({action:'friend-remove',friendship:f.id});}}>フレンド解除</button><button disabled={busy} onClick={()=>{if(window.confirm('この相手をブロックしますか？'))act({action:'friend-block',friendship:f.id});}}>ブロック</button></div><div className="book-grid">{letters.filter(e=>e.friendship===f.id).map(e=><button key={e.id} className="book-card" onClick={()=>open(e)}><span>{e.mine?'あなたから':'フレンドから'}</span><small>{new Date(e.created).toLocaleDateString(locale,{timeZone:'Asia/Tokyo'})}</small><p>{!e.ready?'交換の成立待ち':e.mine?(e.read_at?'相手が開封しました':'相手の開封待ち'):'日記をひらく'}</p><span aria-hidden="true">✉️</span></button>)}</div></div>)}</section></div></Localized>;
}
