'use client';
import ProfileAvatar from './profile-avatar';
import {validProfilePhoto} from '@/lib/profile-image';
import {useEffect,useState} from 'react';
import {profileIcons} from '@/lib/friends';
import {Localized,useLanguage} from './language';
export type Profile={code:string;nickname:string;icon:string;birthday:string;isBirthday:boolean;birthdayGift:boolean};
export type Friend={id:string;status:string;outgoing:boolean;code:string;nickname?:string;icon?:string;birthday?:string};
export default function Friends({profile,friends,letters,incoming,busy,signedIn,act,compose,open}:{profile?:Profile;friends:Friend[];letters:any[];incoming:string[];busy:boolean;signedIn:boolean;act:(d:Record<string,unknown>)=>Promise<any>;compose:(id:string)=>void;open:(e:any)=>void}){
 const {locale}=useLanguage();const [nickname,setNickname]=useState(''),[icon,setIcon]=useState('🐈'),[birthday,setBirthday]=useState(''),[code,setCode]=useState(''),[selected,setSelected]=useState('');
 const [photoBusy,setPhotoBusy]=useState(false),[photoError,setPhotoError]=useState('');
 async function choosePhoto(file?:File){if(!file)return;setPhotoError('');if(file.size>15*1024*1024){setPhotoError('写真は15MB以下で選んでください。');return;}setPhotoBusy(true);const url=URL.createObjectURL(file);try{const img=new Image();await new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=reject;img.src=url;});const canvas=document.createElement('canvas');canvas.width=canvas.height=256;const ctx=canvas.getContext('2d');if(!ctx)throw new Error();const side=Math.min(img.naturalWidth,img.naturalHeight);ctx.fillStyle='#fff';ctx.fillRect(0,0,256,256);ctx.drawImage(img,(img.naturalWidth-side)/2,(img.naturalHeight-side)/2,side,side,0,0,256,256);const photo=canvas.toDataURL('image/jpeg',.82);if(!validProfilePhoto(photo))throw new Error();setIcon(photo);}catch{setPhotoError('写真を読み込めませんでした。JPEG・PNGなど別の写真をお試しください。');}finally{URL.revokeObjectURL(url);setPhotoBusy(false);}}
 useEffect(()=>{setNickname(profile?.nickname??'');setIcon(profile?.icon??'🐈');setBirthday(profile?.birthday??'');},[profile?.nickname,profile?.icon,profile?.birthday]);
 if(!signedIn)return <Localized><div className="empty-state"><h2>フレンド</h2><p>Googleでログインすると、プロフィールとフレンド機能を利用できます。</p><a href="/api/auth/google">Googleでログイン</a></div></Localized>;
 const active=friends.filter(f=>f.status==='accepted');
 return <Localized><div className="friends-page"><div className="page-heading"><div><h1>フレンド</h1><p>知っている誰かと、ひとことずつ。</p></div></div>
 <section className="profile-card profile-book"><div className="profile-book-holes" aria-hidden="true"><i/><i/><i/><i/></div><div className="profile-book-title"><span aria-hidden="true">♡ MY PROFILE ♡</span><h2>わたしのプロフィール帳</h2><p>なかよしのしるし、ここにぺたり。</p></div><form onSubmit={async e=>{e.preventDefault();if(!photoBusy)await act({action:'profile-save',nickname,icon,birthday});}}><div className="profile-photo-area"><div className="profile-polaroid"><ProfileAvatar icon={icon}/><span data-i18n-skip>{nickname||'This is me!'}</span></div><div className="profile-photo-copy"><span className="profile-star" aria-hidden="true">✧</span><label className="photo-upload">{photoBusy?'写真を準備しています…':'写真フォルダから選ぶ'}<input className="sr-only" type="file" accept="image/*" aria-label="プロフィール写真を選ぶ" disabled={busy||photoBusy} onChange={e=>{choosePhoto(e.target.files?.[0]);e.target.value='';}}/></label><small>写真はまんなかを正方形に切り取ります。</small><small>保存するまで、写真は送信されません。</small></div></div>{photoError&&<p role="alert" className="dialog-error">{photoError}</p>}<details className="profile-emoji-picker"><summary>絵文字アイコンもえらべるよ</summary><div className="profile-icons" role="group" aria-label="アイコン">{profileIcons.map(i=><button type="button" key={i} disabled={busy||photoBusy} aria-label={i} aria-pressed={icon===i} onClick={()=>setIcon(i)}>{i}</button>)}</div></details><div className="profile-book-fields"><label><span>ニックネーム</span><input required maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="off" placeholder="なんて呼んだらいい？"/></label><label><span>誕生日（月-日）</span><input value={birthday} placeholder="MM-DD" pattern="[0-9]{2}-[0-9]{2}" maxLength={5} onChange={e=>setBirthday(e.target.value)} inputMode="text"/><small>年は保存しません。例：04-15。未設定でも利用できます。</small></label></div><button className="friend-primary profile-save" disabled={busy||photoBusy}>プロフィールを保存<span aria-hidden="true"> ♡</span></button></form><div className="profile-code-note"><span className="profile-code-stamp" aria-hidden="true">FOR FRIENDS<br/>ONLY ♡</span><label>あなたのフレンドコード<input readOnly value={profile?.code??''} onFocus={e=>e.target.select()} aria-label="あなたのフレンドコード"/></label><p>コードを相手に教えて、申請を承認するとフレンドになります。</p></div><p className="profile-private-note">アイコン・ニックネーム・誕生日は、承認したフレンドだけに表示されます。匿名交換には表示されません。</p></section>
 <section className="profile-card"><h2>フレンドを追加</h2><form onSubmit={async e=>{e.preventDefault();if(await act({action:'friend-request',code:code.replace(/\s/g,'').toUpperCase()}))setCode('');}}><label>相手のフレンドコード<input required value={code} maxLength={32} onChange={e=>setCode(e.target.value)} autoComplete="off"/></label><button className="friend-primary" disabled={busy}>申請を送る</button></form>{friends.filter(f=>f.status==='pending').map(f=><div className="friend-request" key={f.id}><strong data-i18n-skip>{f.code}</strong><span>{f.outgoing?'承認待ち':'フレンド申請が届いています'}</span>{!f.outgoing&&<button disabled={busy} onClick={()=>act({action:'friend-accept',friendship:f.id})}>承認する</button>}<button disabled={busy} onClick={()=>act({action:'friend-remove',friendship:f.id})}>{f.outgoing?'申請を取り消す':'見送る'}</button></div>)}</section>
 <section className="profile-card"><h2>フレンドとの交換日記</h2><p>フレンド宛ては全体で1日1通。双方が投函すると開封できます。日付が違っても交換でき、相手が開封するまでは次の投函を待ちます。</p>{!active.length&&<p>まだフレンドはいません。</p>}<div className="friend-list">{active.map(f=><button key={f.id} className="friend-person" aria-pressed={selected===f.id} onClick={()=>setSelected(f.id)}><ProfileAvatar icon={f.icon}/><span data-i18n-skip>{f.nickname||f.code}</span>{f.birthday&&<small data-i18n-skip>🎂 {f.birthday}</small>}{incoming.includes(f.id)&&<small>お便りが待っています</small>}</button>)}</div>{active.filter(f=>f.id===selected).map(f=><div key={f.id}><div className="friend-actions"><button className="friend-primary" disabled={busy} onClick={()=>compose(f.id)}>このフレンドに書く</button><button disabled={busy} onClick={()=>{if(window.confirm('フレンドを解除しますか？交換途中の日記は取り消されます。'))act({action:'friend-remove',friendship:f.id});}}>フレンド解除</button><button disabled={busy} onClick={()=>{if(window.confirm('この相手をブロックしますか？'))act({action:'friend-block',friendship:f.id});}}>ブロック</button></div><div className="book-grid">{letters.filter(e=>e.friendship===f.id).map(e=><button key={e.id} className="book-card" onClick={()=>open(e)}><span>{e.mine?'あなたから':'フレンドから'}</span><small>{new Date(e.created).toLocaleDateString(locale,{timeZone:'Asia/Tokyo'})}</small><p>{!e.ready?'交換の成立待ち':e.mine?(e.read_at?'相手が開封しました':'相手の開封待ち'):'日記をひらく'}</p><span aria-hidden="true">✉️</span></button>)}</div></div>)}</section></div></Localized>;
}
