'use client';
import {useEffect,useLayoutEffect,useRef,useState} from 'react';
import {ArrowLeft,Send,Mail,MoreHorizontal,UserPlus,ImagePlus,X} from 'lucide-react';
import {readMessagePhoto} from '@/lib/read-profile-photo';
import ProfileAvatar from './profile-avatar';
import PageTitle from './page-title';
import {Localized,useLanguage} from './language';
import {translate} from '@/lib/messages';
import type {Friend} from './profile-panel';
type Event={id:string;key:string;kind:'message'|'diary';hasPhoto?:boolean;mine:boolean;body:string|null;created:number;read_at:number|null;ready:boolean};
type Cursor={created:number;key:string}|null;
async function dmRequest(data:Record<string,unknown>,signal?:AbortSignal){const response=await fetch('/api/diary',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:signal??AbortSignal.timeout(15000)});const body=await response.json() as any;if(!response.ok)throw Object.assign(new Error(body.error||'メッセージを読み込めませんでした。'),{status:response.status});return body;}
export default function Friends({friends,incoming,signedIn,busy,act,compose,open,selected,onSelect,onProfile,manage,refresh,drafts,onDraft}:{friends:Friend[];incoming:string[];signedIn:boolean;busy:boolean;act:(d:Record<string,unknown>)=>Promise<any>;compose:(id:string)=>void;open:(e:any)=>void;selected:string;onSelect:(id:string)=>void;onProfile:(id:string)=>void;manage:()=>void;refresh:()=>void;drafts:Record<string,string>;onDraft:(id:string,value:string,expected?:string)=>void}){
 const {locale}=useLanguage();
 const active=friends.filter(f=>f.status==='accepted').sort((a,b)=>Math.max(b.lastMessageCreated||0,b.lastDiaryCreated||0)-Math.max(a.lastMessageCreated||0,a.lastDiaryCreated||0));
 const friend=active.find(f=>f.id===selected);
 if(!signedIn)return <Localized><div className="empty-state"><h2>フレンド</h2><p>Googleでログインすると、プロフィールとフレンド機能を利用できます。</p><a href="/api/auth/google">Googleでログイン</a></div></Localized>;
 return <Localized><div className="friends-page"><div className="page-heading"><PageTitle headingKey="フレンド"/></div><div className={'dm-layout'+(friend?' has-conversation':'')}>
  <section className="dm-inbox" aria-label="会話一覧"><div className="dm-inbox-heading"><h2>メッセージ</h2><button type="button" onClick={manage} aria-label="プロフィールとフレンド追加"><UserPlus size={21}/>{friends.some(f=>f.status==='pending')&&<i className="dm-dot"/>}</button></div>
  <div className="dm-contact-list">{active.map(f=>{const diary=(f.lastDiaryCreated||0)>(f.lastMessageCreated||0);const date=Math.max(f.lastMessageCreated||0,f.lastDiaryCreated||0);return <div className={'dm-contact'+(f.id===selected?' selected':'')} key={f.id}><button type="button" className="dm-profile-link" onClick={()=>onProfile(f.id)} aria-label={(f.nickname||f.code)+' · '+translate('プロフィール帳',locale)}><ProfileAvatar icon={f.icon}/></button><button type="button" className="dm-contact-open" onClick={()=>onSelect(f.id)} aria-pressed={f.id===selected}><span className="dm-contact-copy"><strong data-i18n-skip>{f.nickname||f.code}</strong><span data-i18n-skip>{diary?translate('日記のお便り',locale):f.lastMessageBody?(f.lastMessageMine?translate('あなた: ',locale):'')+f.lastMessageBody:translate('メッセージを送ってみよう',locale)}</span></span><span className="dm-contact-meta">{date>0&&<time>{new Date(date).toLocaleDateString(locale,{month:'numeric',day:'numeric'})}</time>}{!!f.unread&&<b aria-label={translate('未読メッセージ',locale)}>{f.unread>99?'99+':f.unread}</b>}{incoming.includes(f.id)&&<Mail size={15} aria-label={translate('お便りが待っています',locale)}/>}</span></button></div>;})}{!active.length&&<div className="dm-list-empty"><Mail size={32}/><p>まだフレンドはいません。</p><button onClick={manage}>フレンドを追加</button></div>}</div>
  </section>
  {friend?<Conversation onProfile={()=>onProfile(friend.id)} key={friend.id} friend={friend} incoming={incoming.includes(friend.id)} busy={busy} act={act} compose={compose} open={open} back={()=>onSelect('')} refresh={refresh} draft={drafts[friend.id]||''} onDraft={(value,expected)=>onDraft(friend.id,value,expected)}/>:<section className="dm-empty"><img className="posto-corner" src="/posto-wink.png" alt="" aria-hidden="true"/><span><Send size={47} strokeWidth={1.3}/></span><h2>メッセージ</h2><p>フレンドと、言葉や日記を送り合おう。</p></section>}
 </div></div></Localized>;
}
function Conversation({onProfile,friend,incoming,busy,act,compose,open,back,refresh,draft,onDraft}:{onProfile:()=>void;friend:Friend;incoming:boolean;busy:boolean;act:(d:Record<string,unknown>)=>Promise<any>;compose:(id:string)=>void;open:(e:any)=>void;back:()=>void;refresh:()=>void;draft:string;onDraft:(value:string,expected?:string)=>void}){
 const {locale}=useLanguage();const [photo,setPhoto]=useState(''),[photoBusy,setPhotoBusy]=useState(false);const photoInput=useRef<HTMLInputElement>(null);const [items,setItems]=useState<Event[]>([]),[older,setOlder]=useState<Cursor>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[sending,setSending]=useState(false),[menu,setMenu]=useState(false),[newItems,setNewItems]=useState(false);
 const scroll=useRef<HTMLDivElement>(null),nearBottom=useRef(true),prepend=useRef<number|null>(null),flight=useRef<AbortController|null>(null),alive=useRef(true),initialized=useRef(false),retry=useRef<{body:string;photo:string|null;clientId:string}|null>(null),latestSeen=useRef(0);
 useLayoutEffect(()=>{const el=scroll.current;if(!el)return;if(prepend.current!==null){el.scrollTop+=el.scrollHeight-prepend.current;prepend.current=null;}else if(nearBottom.current)el.scrollTop=el.scrollHeight;},[items]);
 async function load(cursor?:Cursor){
  if(flight.current)return;const controller=new AbortController();flight.current=controller;const timeout=setTimeout(()=>controller.abort(),15000);
  try{const data=await dmRequest({action:'friend-thread',friendship:friend.id,...(cursor?{before:cursor}:{})},controller.signal);if(!alive.current)return;
   const batch=data.items as Event[];
   if(cursor)prepend.current=scroll.current?.scrollHeight??null;
   setItems(previous=>{const gap=!cursor&&previous.length>0&&batch.length>0&&!batch.some(n=>previous.some(p=>p.key===n.key));if(gap){setOlder(data.older);return batch;}const map=new Map(previous.map(e=>[e.key,e]));batch.forEach(e=>map.set(e.key,e));return [...map.values()].sort((a,b)=>a.created-b.created||a.key.localeCompare(b.key));});
   if(!initialized.current||cursor)setOlder(data.older);initialized.current=true;setError('');
   if(!cursor){const newest=batch.at(-1)?.created??0;if(!nearBottom.current&&newest>latestSeen.current)setNewItems(true);latestSeen.current=Math.max(latestSeen.current,newest);}
   const unread=batch.filter(e=>e.kind==='message'&&!e.mine&&!e.read_at).at(-1);
   if(!cursor&&unread&&nearBottom.current&&!document.hidden){await dmRequest({action:'friend-message-read',friendship:friend.id,id:unread.id},controller.signal);refresh();}
  }catch(e){if(alive.current){if((e as any).status===403||(e as any).status===404){setItems([]);refresh();}setError((e as Error).name==='AbortError'?'メッセージを読み込めませんでした。':(e as Error).message);}}
  finally{clearTimeout(timeout);flight.current=null;if(alive.current)setLoading(false);}
 }
 useEffect(()=>{alive.current=true;load();const timer=setInterval(()=>{if(!document.hidden)load();},5000);return()=>{alive.current=false;clearInterval(timer);flight.current?.abort();};},[friend.id]);
 async function choosePhoto(file?:File){if(!file)return;setPhotoBusy(true);setError('');try{const image=await readMessagePhoto(file);if(alive.current)setPhoto(image);}catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setPhotoBusy(false);}}
 async function send(){if(sending||photoBusy||(!draft.trim()&&!photo))return;const body=draft;setSending(true);setError('');const event=retry.current?.body===body&&retry.current.photo===(photo||null)?retry.current:{body,photo:photo||null,clientId:crypto.randomUUID()};retry.current=event;
  try{await dmRequest({action:'friend-message',friendship:friend.id,...event});onDraft('',body);retry.current=null;if(alive.current){setPhoto('');nearBottom.current=true;await load();refresh();}}
  catch(e){if(alive.current)setError((e as Error).message);}finally{if(alive.current)setSending(false);}
 }
 async function read(entry:Event){try{const data=await dmRequest({action:'friend-letter',friendship:friend.id,id:entry.id});if(alive.current)open(data.letter);}catch(e){if(alive.current)setError((e as Error).message);}}
 return <Localized><section className="dm-conversation" aria-label={friend.nickname||friend.code} data-i18n-skip><header className="dm-header"><button className="dm-back" onClick={back} aria-label={translate('会話一覧に戻る',locale)}><ArrowLeft/></button><button type="button" className="dm-profile-link" onClick={onProfile} aria-label={translate('プロフィール帳',locale)}><ProfileAvatar icon={friend.icon}/></button><div><strong>{friend.nickname||friend.code}</strong>{friend.birthday&&<small>🎂 {friend.birthday}</small>}</div><button className="dm-options" onClick={()=>setMenu(v=>!v)} aria-expanded={menu} aria-label={translate('会話の設定',locale)}><MoreHorizontal/></button></header>
 {menu&&<div className="dm-settings"><button disabled={busy} onClick={async()=>{if(window.confirm(translate('フレンドを解除しますか？交換途中の日記は取り消されます。',locale))){if(await act({action:'friend-remove',friendship:friend.id}))back();}}}>{translate('フレンド解除',locale)}</button><button disabled={busy} onClick={async()=>{if(window.confirm(translate('この相手をブロックしますか？',locale))){if(await act({action:'friend-block',friendship:friend.id}))back();}}}>{translate('ブロック',locale)}</button></div>}
 <div className="dm-timeline" ref={scroll} onScroll={()=>{const el=scroll.current;if(el){nearBottom.current=el.scrollHeight-el.scrollTop-el.clientHeight<70;if(nearBottom.current)setNewItems(false);}}}>
 {older&&<button className="dm-older" onClick={()=>load(older)}>{translate('以前のやり取り',locale)}</button>}{loading&&<p className="dm-status" role="status">{translate('読み込み中',locale)}</p>}{!loading&&!items.length&&<div className="dm-greeting"><button type="button" className="dm-profile-link" onClick={onProfile} aria-label={translate('プロフィール帳',locale)}><ProfileAvatar icon={friend.icon}/></button><strong>{friend.nickname||friend.code}</strong><p>{translate('メッセージを送ってみよう',locale)}</p></div>}
 {items.map((item,i)=>{const date=new Date(item.created);const dateText=date.toLocaleDateString(locale,{year:'numeric',month:'short',day:'numeric'});const previous=items[i-1];return <div key={item.key}>{(!previous||new Date(previous.created).toDateString()!==date.toDateString())&&<p className="dm-day">{dateText}</p>}<div className={'dm-event '+(item.mine?'mine':'theirs')}>{!item.mine&&<button type="button" className="dm-profile-link" onClick={onProfile} aria-label={translate('プロフィール帳',locale)}><ProfileAvatar icon={friend.icon}/></button>}<div className="dm-event-content">{item.kind==='message'?<>{!!item.hasPhoto&&<MessagePhoto id={item.id} friendship={friend.id} onReady={()=>{if(nearBottom.current&&scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;}}/>} {!!item.body&&<p className="dm-bubble">{item.body}</p>}</>:<button className="dm-diary" onClick={()=>read(item)}><Mail size={30}/><strong>{translate('交換日記',locale)}</strong><span>{translate(!item.ready?'交換の成立待ち':item.mine?'あなたから':'日記をひらく',locale)}</span></button>}<small className="dm-event-meta">{date.toLocaleTimeString(locale,{hour:'2-digit',minute:'2-digit'})}{item.mine&&item.read_at?' · '+translate('既読',locale):''}</small></div></div></div>;})}
 </div>{newItems&&<button className="dm-new" onClick={()=>{nearBottom.current=true;setNewItems(false);if(scroll.current)scroll.current.scrollTop=scroll.current.scrollHeight;load();}}>{translate('新しいメッセージ',locale)} ↓</button>}
 {incoming&&<div className="dm-waiting"><Mail size={16}/>{translate('お便りが待っています',locale)}</div>}
 {error&&<div className="dm-error" role="alert">{translate(error,locale)}<button onClick={()=>load()}>{translate('再読み込み',locale)}</button></div>}
 <input ref={photoInput} className="sr-only" type="file" accept="image/*" aria-label={translate('写真を選ぶ',locale)} disabled={sending||photoBusy} onChange={e=>{choosePhoto(e.currentTarget.files?.[0]);e.currentTarget.value='';}}/>{photoBusy&&<p className="dm-status" role="status">{translate('写真を準備しています…',locale)}</p>}{photo&&<div className="dm-photo-preview"><img src={photo} alt={translate('送信する写真',locale)}/><button type="button" disabled={sending} onClick={()=>setPhoto('')} aria-label={translate('写真を外す',locale)}><X size={20}/></button></div>}
 <form className="dm-composer" onSubmit={e=>{e.preventDefault();send();}}><button className="dm-write-diary" type="button" onClick={()=>compose(friend.id)} disabled={busy||sending} aria-label={translate('このフレンドに書く',locale)} title={translate('このフレンドに書く',locale)}><Mail size={22}/></button><button type="button" disabled={sending||photoBusy} onClick={()=>photoInput.current?.click()} aria-label={translate('写真を選ぶ',locale)}><ImagePlus size={22}/></button><textarea aria-label={translate('メッセージ',locale)} placeholder={translate('メッセージを入力…',locale)} rows={1} maxLength={1000} value={draft} onChange={e=>onDraft(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&(e.ctrlKey||e.metaKey)&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><button type="submit" disabled={sending||photoBusy||(!draft.trim()&&!photo)} aria-label={translate('送信',locale)}><Send size={21}/></button></form>
 </section></Localized>;
}

function MessagePhoto({id,friendship,onReady}:{id:string;friendship:string;onReady:()=>void}){
 const {locale}=useLanguage();const [src,setSrc]=useState(''),[error,setError]=useState(false),[attempt,setAttempt]=useState(0);const box=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const controller=new AbortController();let started=false;const observer=new IntersectionObserver(entries=>{if(started||!entries.some(e=>e.isIntersecting))return;started=true;observer.disconnect();dmRequest({action:'friend-photo',friendship,id},controller.signal).then(data=>{if(!controller.signal.aborted)setSrc(data.photo);}).catch(()=>{if(!controller.signal.aborted)setError(true);});},{rootMargin:'200px'});if(box.current)observer.observe(box.current);return()=>{observer.disconnect();controller.abort();};},[id,friendship,attempt]);
 return <div ref={box}>{src?<><button type="button" className="dm-photo" onClick={()=>dialog.current?.showModal()} aria-label={translate('写真を拡大',locale)}><img src={src} onLoad={onReady} alt={translate('写真',locale)}/></button><dialog className="dm-photo-dialog" ref={dialog} aria-label={translate('写真',locale)} onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}}><button type="button" onClick={()=>dialog.current?.close()} aria-label={translate('閉じる',locale)}><X/></button><img src={src} alt={translate('写真',locale)}/></dialog></>:<button type="button" className="dm-photo-status" disabled={!error} onClick={()=>{setError(false);setAttempt(n=>n+1);}}>{translate(error?'再読み込み':'読み込み中',locale)} 📷</button>}</div>;
}
