'use client';
import PageTitle from './page-title';
import ProfileCard,{favoriteLabels} from './profile-card';
import {readProfileDetails,profileColors,profileThemes,favoriteFields} from '@/lib/profile-details';
import {defaultStickerLayout} from '@/lib/sticker-layout';
import {translate} from '@/lib/messages';
import {readProfilePhoto} from '@/lib/read-profile-photo';
import {useEffect,useState} from 'react';
import ProfilePager from './profile-pager';
import {profileIcons} from '@/lib/friends';
import {Localized,useLanguage} from './language';
export type Profile={details?:string;code:string;nickname:string;icon:string;birthday:string;isBirthday:boolean;birthdayGift:boolean};
export type Friend={details?:string;id:string;status:string;outgoing:boolean;code:string;nickname?:string;icon?:string;birthday?:string;lastMessageBody?:string;lastMessageCreated?:number;lastMessageMine?:boolean;lastDiaryCreated?:number;unread?:number};
export default function ProfilePanel({profile,friends,busy,signedIn,act,acquired=[],targetId='self'}:{profile?:Profile;targetId?:string;acquired?:string[];friends:Friend[];busy:boolean;signedIn:boolean;act:(d:Record<string,unknown>)=>Promise<any>}){
 const {locale}=useLanguage();const [nickname,setNickname]=useState(''),[icon,setIcon]=useState('🐈'),[birthday,setBirthday]=useState(''),[code,setCode]=useState('');
 const [details,setDetails]=useState(()=>readProfileDetails(profile?.details));
 const [editing,setEditing]=useState(false);
 const [photoBusy,setPhotoBusy]=useState(false),[photoError,setPhotoError]=useState('');
 const [copied,setCopied]=useState(false),[copyError,setCopyError]=useState(false);
 useEffect(()=>{if(!copied)return;const timer=setTimeout(()=>setCopied(false),2500);return()=>clearTimeout(timer);},[copied]);
 async function copyCode(){if(!profile?.code)return;setCopyError(false);try{await navigator.clipboard.writeText(profile.code);setCopied(true);}catch{setCopyError(true);}}
 async function choosePhoto(file?:File){if(!file)return;setPhotoError('');if(file.size>15*1024*1024){setPhotoError('写真は15MB以下で選んでください。');return;}setPhotoBusy(true);try{setIcon(await readProfilePhoto(file));}catch{setPhotoError('写真を読み込めませんでした。JPEG・PNGなど別の写真をお試しください。');}finally{setPhotoBusy(false);}}

 useEffect(()=>{setDetails(readProfileDetails(profile?.details));setNickname(profile?.nickname??'');setIcon(profile?.icon??'🐈');setBirthday((profile?.birthday??'').replace('-',''));},[profile?.nickname,profile?.icon,profile?.birthday,profile?.details]);
 if(!signedIn)return <Localized><div className="empty-state"><div className="page-heading"><PageTitle headingKey="フレンド"/></div><p>Googleでログインすると、プロフィールとフレンド機能を利用できます。</p><a href="/api/auth/google">Googleでログイン</a></div></Localized>;
 const accepted=friends.filter(f=>f.status==='accepted');
 const themeLabels={stars:'星くず',gingham:'ギンガム',dots:'水玉',letter:'お手紙'};
 const colorLabels={lavender:'ラベンダー',sky:'空色',peach:'桃色',mint:'ミント',cream:'クリーム'};
 function beginEdit(){setDetails(readProfileDetails(profile?.details));setNickname(profile?.nickname||'');setIcon(profile?.icon||'🐈');setBirthday((profile?.birthday||'').replace('-',''));setEditing(true);}
 return <Localized><div className="friends-page"><div className="page-heading"><h1 className="handwritten-heading" data-i18n-skip>{locale==='ja'?<img src="/heading-profile.svg" alt="プロフィール"/>:translate('プロフィール',locale)}</h1></div>
 <ProfilePager targetId={targetId} labels={[nickname||translate('わたし',locale),...accepted.map(f=>f.nickname||f.code)]} ids={['self',...accepted.map(f=>f.id)]}>
 <div><ProfileCard nickname={editing?nickname:profile?.nickname} icon={editing?icon:profile?.icon} birthday={editing&&birthday.length===4?birthday.slice(0,2)+'-'+birthday.slice(2):profile?.birthday} details={editing?details:readProfileDetails(profile?.details)} disabled={busy||photoBusy} onStickerChange={editing?(index,layout)=>setDetails(d=>({...d,stickers:d.stickers.map((s,i)=>i===index?{...s,layout}:s)})):undefined}/><button className="profile-edit-link" onClick={beginEdit} disabled={editing}>プロフィールを編集</button></div>
 {accepted.map(f=><ProfileCard isFriend key={f.id} nickname={f.nickname} icon={f.icon} birthday={f.birthday} details={readProfileDetails(f.details)}/>)}</ProfilePager>
 {editing&&<section className="profile-card profile-editor"><h2>わたしらしく飾る</h2><form onSubmit={async e=>{e.preventDefault();if(!photoBusy&&await act({action:'profile-save',nickname,icon,birthday,details}))setEditing(false);}}>
 <label className="photo-upload">{photoBusy?'写真を準備しています…':'写真フォルダから選ぶ'}<input className="sr-only" type="file" accept="image/*" aria-label="プロフィール写真を選ぶ" disabled={busy||photoBusy} onChange={async e=>{const input=e.currentTarget;await choosePhoto(input.files?.[0]);input.value='';}}/></label>{photoError&&<p role="alert" className="dialog-error">{photoError}</p>}
 <details className="profile-emoji-picker"><summary>絵文字アイコンもえらべるよ</summary><div className="profile-icons" role="group" aria-label="アイコン">{profileIcons.map(i=><button type="button" key={i} disabled={busy||photoBusy} aria-label={i} aria-pressed={icon===i} onClick={()=>setIcon(i)}>{i}</button>)}</div></details>
 <div className="profile-edit-fields"><label>ニックネーム<input required maxLength={24} value={nickname} onChange={e=>setNickname(e.target.value)} autoComplete="off"/></label><label>誕生日（4桁）<input value={birthday} placeholder="0415" pattern="[0-9]{4}" maxLength={4} onChange={e=>setBirthday(e.target.value.replace(/[^0-9]/g,''))} inputMode="numeric"/></label>{favoriteFields.map(k=><label key={k}>{translate(favoriteLabels[k],locale)}<input maxLength={40} value={details.favorites[k]} onChange={e=>setDetails(d=>({...d,favorites:{...d.favorites,[k]:e.target.value}}))}/></label>)}</div>
 <fieldset><legend>背景</legend><div className="profile-custom-choices">{profileThemes.map(t=><button type="button" key={t} aria-pressed={details.theme===t} onClick={()=>setDetails(d=>({...d,theme:t}))}>{translate(themeLabels[t],locale)}</button>)}</div></fieldset><fieldset><legend>色</legend><div className="profile-custom-choices">{profileColors.map(c=><button className={'profile-color-'+c} type="button" key={c} aria-pressed={details.color===c} onClick={()=>setDetails(d=>({...d,color:c}))}>{translate(colorLabels[c],locale)}</button>)}</div></fieldset>
 <fieldset><legend>ステッカー <small>{details.stickers.length} / 5</small></legend><div className="profile-custom-choices">{[...new Set(acquired)].filter(i=>!i.startsWith('paper-')).map(item=><button type="button" key={item} disabled={details.stickers.length>=5} aria-label={item} onClick={()=>setDetails(d=>({...d,stickers:[...d.stickers,{sticker:item,layout:{...defaultStickerLayout,x:75,y:20}}]}))}>{item}</button>)}</div><p>プロフィールには獲得済みステッカーを繰り返し使えます。枚数は消費しません。</p><div className="profile-custom-choices">{details.stickers.map((s,i)=><button key={i} type="button" onClick={()=>setDetails(d=>({...d,stickers:d.stickers.filter((_,n)=>n!==i)}))} aria-label={translate('ステッカー{number}を外す',locale,{number:i+1})}>{s.sticker} ×</button>)}</div></fieldset><div className="profile-editor-actions"><button className="friend-primary" disabled={busy||photoBusy}>プロフィールを保存</button><button type="button" disabled={busy||photoBusy} onClick={()=>{setEditing(false);setNickname(profile?.nickname||'');}}>キャンセル</button></div></form></section>}
 <div className="profile-card profile-code-compact"><label>あなたのフレンドコード<span className="friend-code-copy"><input readOnly value={profile?.code??''} onFocus={e=>e.target.select()} aria-label="あなたのフレンドコード"/><button type="button" disabled={!profile?.code} onClick={copyCode}>{copied?'コピー済み':'コピー'}</button></span></label>{copyError&&<p role="alert">コピーできませんでした。コードを選択してコピーしてください。</p>}</div><p className="profile-private-note">プロフィール帳は承認済みフレンドにのみ公開されます。</p>
 <section className="profile-card"><h2>フレンドを追加</h2><form onSubmit={async e=>{e.preventDefault();if(await act({action:'friend-request',code:code.replace(/\s/g,'').toUpperCase()}))setCode('');}}><label>相手のフレンドコード<input required value={code} maxLength={32} onChange={e=>setCode(e.target.value)} autoComplete="off"/></label><button className="friend-primary" disabled={busy}>申請を送る</button></form>{friends.filter(f=>f.status==='pending').map(f=><div className="friend-request" key={f.id}><strong data-i18n-skip>{f.code}</strong><span>{f.outgoing?'承認待ち':'フレンド申請が届いています'}</span>{!f.outgoing&&<button disabled={busy} onClick={()=>act({action:'friend-accept',friendship:f.id})}>承認する</button>}<button disabled={busy} onClick={()=>act({action:'friend-remove',friendship:f.id})}>{f.outgoing?'申請を取り消す':'見送る'}</button></div>)}</section></div></Localized>;
}
